name: sp_assignment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2  # Correct version for shared_preferences
  lottie: ^2.7.0  # Correct version for Lottie animations
  cupertino_icons: ^1.0.8  # iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Recommended lints for good coding practices

flutter:
  uses-material-design: true

  assets:
    - assets/mobile.json  # Make sure this file exists
